title: Anastasia Iskaliyeva
logo: /photo.png
description: >
  Data Scientist 
  <br><br>
  Irvine, CA
  <br><br>
  Contact
  <br><br>
  Resume
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
